@isTest
private class LeadConvertTriggerTest {
    // // Cria um lead e o converte, depois verifica se a ação foi bem sucedida
    // @isTest 
    // static void TestLeadConvert() {
    //     // Teste setup: inserir lead
    //     Lead lead = new Lead(
    //         FirstName='Test',
    //         LastName='Conversion', 
    //         Phone='+5531986551353',
    //         guid__c = 'TesteGuid',
    //         NumeroProposta__c = 2504,
    //         CPF__c = '318.610.810-14'
    //     );
    //     insert lead;
        
    //     // Execução do teste
    //     Test.startTest();
    //     Database.LeadConvert lc = new database.LeadConvert();
    //     lc.setLeadId(lead.id);
    //     lc.setDoNotCreateOpportunity(false);
    //     lc.setConvertedStatus('Reunião Agendada');
    //     Database.LeadConvertResult lcr = Database.convertLead(lc);
    //     Test.stopTest(); 

    //     //Asserções do teste
    //     System.assert(lcr.isSuccess());
    // }
}