@isTest
public  class UpdateWhatsAppNumberTest {
    // @isTest
    // public static void UpdateWhatsAppNumberTest() {
    //     // Cria um Lead com um número de telefone.
    //     Lead lead = new Lead(
    //         FirstName = 'Wender',
    //         LastName = 'Carvalho',
    //         Phone = '+5531986551353'
    //     );
    //     insert lead;
        
    //     // Verifica se o campo "Numero_de_WhatsApp__c" foi atualizado com o número de telefone.
    //     lead = [SELECT Numero_de_WhatsApp__c FROM Lead WHERE Id = :lead.Id];
    //     System.assertEquals('whatsapp:+553186551353', lead.Numero_de_WhatsApp__c);
        
    //     // Atualiza o número de telefone do Lead.
    //     lead.Phone = '(31)99393-9209';
    //     update lead;
        
    //     // Verifica se o campo "Numero_de_WhatsApp__c" foi atualizado com o novo número de telefone.
    //     lead = [SELECT Numero_de_WhatsApp__c FROM Lead WHERE Id = :lead.Id];
    //     System.assertEquals('whatsapp:+553193939209', lead.Numero_de_WhatsApp__c);
        
    //     // Cria um Lead sem número de telefone.
    //     Lead lead2 = new Lead(
    //         FirstName = 'Teste Teste',
    //         LastName = 'Lead Trigger',
    //         Company = 'Bow-e'
    //     );
    //     insert lead2;
        
    //     // Verifica se o campo "Numero_de_WhatsApp__c" não foi atualizado.
    //     lead2 = [SELECT Numero_de_WhatsApp__c FROM Lead WHERE Id = :lead2.Id];
    //     System.assertEquals(null, lead2.Numero_de_WhatsApp__c);
    // }
}